version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: tricking
      MYSQL_DATABASE: tricking3d-test
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

volumes:
  db-data: